### ISSUE TITLE
MOO for multi-class classification

### ISSUE THREAD

**Issue by dbmptr** [Swiggy/Moo-GBT#1]
Hi,
Dose the current package support constraints for multi-class classification? I believe the constraints affect the overall training by altering the leaf node values in the `_update_terminal_region` member function, which is implemented in each loss function class. But I see that only for `LeastSquaresError`  and `BinomialDeviance` classes, the additional labels are being used to impose constraints. Is there any other place in the code where constraints are used to affect the multi-class loss, i.e. `MultinomialDeviance` ?

Thanks,
Deb

**Comment by bhavi289** [comment]
Multi-objective is only supported for 2 loss functions now - `LeastSquaresError` and `BinomialDeviance`.
`MultinomialDeviance` is not supported as of now.
